examples/src/app.jsx
src/components/profile-card.jsx

Adjusted style of avatar in profile card.

:art: Style adjustment

---

src/style/avatars.js
src/style/badges.js
src/style/buttons.js
src/style/channel-header.js
src/style/inputs.js
src/style/lists.js
src/style/messages.js
src/style/profile-cards.js

Style order

---

src/components/list.jsx

removed spread props operator

---

src/style/lists.js

:lipstick: Added borders

---

README.md
src/components/button.jsx

Adjusted Element to Node where needed. #90 
will fix #90

:bug: Element to Node

---

README.md
src/components/alert.jsx
src/components/app-header.jsx
src/components/avatar.jsx
src/components/badge.jsx
src/components/channel-header.jsx
src/components/empty-state.jsx
src/components/list-item.jsx
src/components/profile-card.jsx

:bug: Fixed propTypes

---

examples/src/pop-up.jsx
src/components/button.jsx

:lipstick: Added inverted styles

---

examples/src/app.jsx
src/components/message.jsx
src/style/messages.js

Messages come from bottom first now. #103 #113

:lipstick: Scroll from bottom first

---

src/components/badge.jsx
src/components/button.jsx

:bug: Fixed inverted styles without theme for Badge and Button

---

src/style/app-header.js

Updated styles off app header.

:lipstick: Style updated.

---

package.json

Moved emojione and color to Dependencies. closes #150.

:wrench: Moved peerDependencies to Dependencies.

---

src/message/index.jsx
src/style/messages.js

:bug: Message styles.

---

docs/components.json
examples/src/app.jsx
src/message/index.jsx

Issue #190

---

src/index.js
src/menu-item/index.jsx
src/style/menu-item.js

:sparkles: Added MenuItem

---

src/select/index.jsx
src/select/styles.js

:bug: Added missing lineHeight

---

package.json
src/message/index.jsx

:bug: Removed marginBottom from compact header

---

docs.sh

:bug: Changed rm command

---

src/profile-card/styles.js

:lipstick: Changed fontsize

---

examples/src/app.jsx
src/tab/get-styles.js
src/tab/index.jsx
src/tab/styles.js
test/tab/get-styles.test.js

:sparkles: Added optional badge to Tab

---

examples/src/app.jsx
src/radio-button-group/index.jsx

:art: Moved onChange to RadioButtonGroup

---

src/search-box/index.jsx

:bug: Deconstructed props

---

examples/src/app.jsx
src/tab/get-styles.js
src/tab/index.jsx
src/tab/styles.js
test/tab/get-styles.test.js

:lipstick: Changed Tab style

---

src/dialog/styles.js
src/modal/styles.js

:lipstick: Added boxShadow

---

examples/src/app.jsx
src/tabs/index.jsx

:sparkles: Added initialSelectedIndex to Tabs

---

src/message/styles.js

:bug: Added width and height to img tag

---

src/button/styles.js

:bug: Fixed button flex problem.

---

examples/src/profile.jsx
src/profile/styles.js

:bug: Profile header bug.

---

docs/components.json
src/profile-card/get-styles.js
src/profile-card/index.jsx

Issue #410

---

src/settings/colors.js

:bug: Changed bg color of inputs.

---

src/alert/index.jsx
src/alert/styles.js

:bug: Changed alert styles.

---

src/message/get-styles.js
src/message/styles.js

maxWidth and Height on images

---

docs/src/components/input.jsx
src/input/styles.js

To fit with other page styles.

Fixed styling for Input page

---

docs/src/components/icon-menu.jsx
docs/src/components/pop-over.jsx
src/list-item/get-styles.js
src/list-item/index.jsx
src/list-item/styles.js

All use of "style={{ }}" has been corrected now.

Issue-#451: Fixed last few "style={{ }}"s

---

docs/src/components/admin-badge.jsx
docs/src/components/badge.jsx
docs/src/components/button.jsx

All components should have all available examples now.

Issue #446: Added examples to components

---

docs/components.json
docs/src/components/avatar.jsx
src/avatar/get-styles.js
src/avatar/index.jsx
src/avatar/styles.js
src/settings/colors.js

:sparkles: Added status indicator to Avatar

---

src/with-theme/index.jsx

:zap: Added recompose pure to WithTheme

---

docs/components.json
docs/src/components/message.jsx
src/message/index.jsx

Issue #493

---

test/admin-badge/get-styles.test.js

https://github.com/anchorchat/anchor-ui/issues/203

Issue #203 admin-badge

---

src/admin-badge/styles.js
src/app-header/get-styles.js
src/app-header/styles.js
src/checkbox/index.jsx
src/dialog/styles.js
src/style/badges.js
src/style/loaders.js
src/style/switch.js
src/switch/index.jsx
src/tab/styles.js
src/table-header/styles.js
test/app-header/get-styles.test.js

:lipstick: Added theme color transition

---

src/list/index.jsx
src/list/styles.js

Issue #203 list

---

src/list-item/get-styles.js
test/list-item/get-styles.test.js

Issue #203 list-item

---

src/message/image-message/get-styles.js
test/message/image-message-get-styles.test.js

Issue #203 image-message

---

docs/src/components/message.jsx
docs/src/index.css
src/message/text-message/index.jsx

:hankey: Possible fix.

---

docs/src/components/list-item.jsx
src/list-item/get-styles.js
src/list-item/index.jsx
src/list-item/styles.js
test/list-item/get-styles.test.js

:lipstick: Fixed height for list-items without second line.

---

src/select/get-styles.js
src/select/styles.js
test/select/get-styles.test.js

:lipstick: Added translate

---

test/admin-badge/index.test.js
test/alert/index.test.js
test/profile/index.test.js

AdminBadge component test

---

src/list-item/get-styles.js
src/list-item/index.jsx
src/list-item/styles.js
test/list-item/get-styles.test.js

:hammer: Refactored list-item to fix alignment issue.

---

test/app-header/index.test.js
test/profile/index.test.js

Appheader component test

---

test/badge/index.test.js

Badge component test

---

docs/components.json
docs/src/components/message.jsx
src/commands/index.jsx
src/message/index.jsx
src/message/message-time/get-styles.js
src/message/message-time/index.jsx
src/message/message-time/styles.js
src/message/text-message/index.jsx
test/message/message-time-get-styles.test.js

Added edited node to message time

---

test/divider/index.test.js

Divider component test

---

src/pop-over/styles.js

:lipstick: It's over nine thousand!

---

test/admin-badge/index.test.js
test/alert/index.test.js
test/app-header/index.test.js
test/avatar/index.test.js
test/badge/index.test.js
test/button/index.test.js
test/card-content/index.test.js
test/card-header/index.test.js
test/card/index.test.js
test/channel-header/index.test.js
test/checkbox/index.test.js
test/dialog/index.test.js
test/divider/index.test.js
test/empty-state/index.test.js
test/input/index.test.js
test/list/index.test.js
test/profile/index.test.js

Component tests: Props fixes

---

test/table-body/index.test.js
test/table-column/index.test.js
test/table-header-column/index.test.js
test/table-header/index.test.js
test/table-row/index.test.js
test/table/index.test.js

Table component test

---

test/tab/index.test.js

Tab component test

---

test/slider/index.test.js

Slider component test

---

test/alert/index.test.js
test/button/index.test.js
test/dialog/index.test.js
test/lightbox/index.test.js
test/menu-item/index.test.js

Component tests: Added onClick tests

---

src/internal/get-pop-over-position.js
test/internal/get-pop-over-position.test.js

Issue #605

---

test/menu/index.test.js

Menu component test

---

test/checkbox/index.test.js
test/input/index.test.js
test/radio-button/index.test.js
test/slider/index.test.js
test/tab/index.test.js

Component tests: Added onChange tests

---

src/button/styles.js
src/input/index.jsx
src/input/styles.js
src/message-input/styles.js
src/settings/colors.js
src/slider/styles.js
test/button/get-styles.test.js
test/input/get-styles.test.js
test/slider/get-styles.test.js

:lipstick: Adjusted styles to conform with design.

---

src/list-item/index.jsx
src/list-item/styles.js

Removed z-index to overcome z-index quirks & restructured avatar div order.

List-item bug

---

test/admin-badge/get-styles.test.js
test/admin-badge/index.test.js

Issue #552 admin badge

---

src/alert/component.jsx
src/alert/get-styles.js
src/alert/index.js
test/alert/get-styles.test.js
test/alert/index.test.js

Issue #552 alert

---

src/app-header/component.jsx
src/app-header/get-styles.js
src/app-header/index.js
test/app-header/get-styles.test.js
test/app-header/index.test.js

Issue #552 app header

---

src/avatar/component.jsx
src/avatar/index.js
test/avatar/get-styles.test.js
test/avatar/index.test.js

Issue #552 avatar

---

src/banner/component.jsx
src/banner/index.js
test/banner/get-styles.test.js
test/banner/index.test.js

Issue #552 banner

---

src/message/text-message/index.jsx

Added a check for numbers followed by "." to overcome Catastrophic Backtracking regexp.

Url regexp

---

src/checkbox/component.jsx
src/checkbox/index.js
test/checkbox/get-styles.test.js
test/checkbox/index.test.js

Forgot to push `index.test.js` changes...

Issue #552 checkbox

---

src/input/component.jsx
src/input/index.js
test/input/get-styles.test.js
test/input/index.test.js

Issue #552 input

---

docs/components.json
docs/src/components/radio-button.jsx
src/radio-button-group/index.jsx
src/radio-button/index.jsx
src/select/component.jsx
src/select/index.js
src/switch/index.jsx

Sjaakluthart/issue #1024
